### ISSUE TITLE
Unable to collect metrics with more than one budget

### ISSUE THREAD

**Issue by jtoniolo** [mcbobke/ynab-exporter#3]
The collector isn't behaving correctly when more than one budget exists. It attempts to collect the same metric more than once.

### Steps to reproduce:

1. Have a budget with data in it
2. Use YNAB's "Make a fresh start" feature. This effectively copies the currently selected budget, without any transactions or budget amounts. The accounts and categories will all have identical names to the original.
3. Add budget amounts and transactions to the new "fresh" budget
4. Browse to the ynab_exporter's metrics endpoint.

### Errors on at the metrics endpoint:
```
96 error(s) occurred:
* collected metric "ynab_category_budgeted" { label:{name:"category_group_name" value:"Internal Master Category"} label:{name:"category_name" value:"Inflow: Ready to Assign"} gauge:{value:0}} was collected before with the same name and label values
```

### Suggestion
An easy fix might be to add an env var to allow specifying which budget to use. Ideally, it should handle multiple budgets, but having an exporter per budget is workable.

**Comment by mcbobke** [comment]
It will be easy enough for this to handle multiple budgets - I wrote this exporter originally as a project to drive myself to learn Go, and it's surely got some things to come back to and refactor.

Thanks for the submission, I'll prepare a fix.

**Comment by mcbobke** [comment]
[v1.0.0](https://github.com/mcbobke/ynab-exporter/releases/tag/v1.0.0) is now released and pushed. Thanks again!
